import React from "react";

import {
  LayoutDashboard,
  ArrowUpRight,
  ArrowDownLeft,
  ArrowRightLeft,
  Wallet,
  CreditCard,
  Plus,
  Filter,
  Calendar,
  Tag,
  AlertCircle,
  MoreVertical,
  Trash2,
  CheckCircle2,
  Clock,
  Users,
  Copy,
  Check,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Settings,
  BarChart3,
  User,
  LogOut,
  LineChart as LineChartIcon,
  ListTree,
  UserPlus,
  CornerDownLeft,
  ShoppingBag,
  Car,
  Home,
  Coffee,
  Utensils,
  Plane,
  Briefcase,
  Zap,
  Smartphone,
  Heart,
  Gift,
  Book,
  HelpCircle,
  ShoppingCart,
  Fuel,
  Bus,
  Bike,
  GraduationCap,
  Baby,
  PawPrint,
  Dumbbell,
  Music,
  Tv,
  Gamepad2,
  Scissors,
  Stethoscope,
  Pill,
  Building2,
  Landmark,
  HandCoins,
  PiggyBank,
  Banknote,
  Receipt,
  Shirt,
  Umbrella,
  Wrench,
  Paintbrush,
  Camera,
  TreePine,
  UtensilsCrossed,
  Wine,
  IceCream,
  Pizza,
  Salad,
  Droplets,
  Wifi,
  Globe,
  PartyPopper,
  Theater,
  Headphones,
  Church,
  Star,
  Menu,
  X,
} from "lucide-react";

export const COLORS = [
  "#98e5dd",
  "#3b82f6",
  "#f59e0b",
  "#ef4444",
  "#8b5cf6",
  "#ec4899",
];

export const CATEGORY_ICONS = {
  // Finanças
  Wallet: <Wallet size={16} />,
  CreditCard: <CreditCard size={16} />,
  Banknote: <Banknote size={16} />,
  PiggyBank: <PiggyBank size={16} />,
  HandCoins: <HandCoins size={16} />,
  Receipt: <Receipt size={16} />,
  Landmark: <Landmark size={16} />,
  Building2: <Building2 size={16} />,
  // Compras & Varejo
  Tag: <Tag size={16} />,
  ShoppingBag: <ShoppingBag size={16} />,
  ShoppingCart: <ShoppingCart size={16} />,
  Shirt: <Shirt size={16} />,
  // Transporte
  Car: <Car size={16} />,
  Fuel: <Fuel size={16} />,
  Bus: <Bus size={16} />,
  Bike: <Bike size={16} />,
  Plane: <Plane size={16} />,
  // Casa & Moradia
  Home: <Home size={16} />,
  Zap: <Zap size={16} />,
  Droplets: <Droplets size={16} />,
  Wifi: <Wifi size={16} />,
  Wrench: <Wrench size={16} />,
  Paintbrush: <Paintbrush size={16} />,
  Umbrella: <Umbrella size={16} />,
  // Alimentação
  Coffee: <Coffee size={16} />,
  Utensils: <Utensils size={16} />,
  UtensilsCrossed: <UtensilsCrossed size={16} />,
  Pizza: <Pizza size={16} />,
  Salad: <Salad size={16} />,
  Wine: <Wine size={16} />,
  IceCream: <IceCream size={16} />,
  // Trabalho & Educação
  Briefcase: <Briefcase size={16} />,
  GraduationCap: <GraduationCap size={16} />,
  Book: <Book size={16} />,
  Globe: <Globe size={16} />,
  // Saúde & Bem-estar
  Heart: <Heart size={16} />,
  Stethoscope: <Stethoscope size={16} />,
  Pill: <Pill size={16} />,
  Dumbbell: <Dumbbell size={16} />,
  // Entretenimento & Lazer
  Tv: <Tv size={16} />,
  Gamepad2: <Gamepad2 size={16} />,
  Music: <Music size={16} />,
  Headphones: <Headphones size={16} />,
  Camera: <Camera size={16} />,
  Theater: <Theater size={16} />,
  PartyPopper: <PartyPopper size={16} />,
  // Família & Pessoal
  Baby: <Baby size={16} />,
  PawPrint: <PawPrint size={16} />,
  Gift: <Gift size={16} />,
  Scissors: <Scissors size={16} />,
  Church: <Church size={16} />,
  Star: <Star size={16} />,
  // Tecnologia
  Smartphone: <Smartphone size={16} />,
  TreePine: <TreePine size={16} />,
};

